version: "3.8"
services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - .:/data
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  ats:
    build:
      context: ./ats
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - .:/data
    depends_on:
      - nginx
  hey:
    build:
      context: ./hey
    command: /go/bin/hey -c 32 -q 8 -z 1s -m PUT -D /src/hex-1KiB.dat -random-request-id http://ats
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - ats
  # curl:
  #   image: curlimages/curl:8.5.0
  #   command: curl -sSD - http://ats
  #   depends_on:
  #     - ats
