version: "3.8"
services:
  nginx:
    build:
      context: ./nginx
  ats:
    build:
      context: ./ats
    depends_on:
      - nginx
  hey:
    build:
      context: ./hey
    command: /go/bin/hey -c 20 -q 10 -z 5s -m PUT -D /src/a-1KiB.dat -random-request-id http://ats
    depends_on:
      - ats
  # curl:
  #   image: curlimages/curl:8.5.0
  #   command: curl -sSD - http://ats
  #   depends_on:
  #     - ats
