version: "3.8"
services:
  nginx:
    build:
      context: ./nginx
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  ats:
    build:
      context: ./ats
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - nginx
  hey:
    build:
      context: ./hey
    command: /go/bin/hey -c 40 -q 40 -z 5s -m PUT -D /src/a-1KiB.dat -random-request-id http://ats
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - ats
  # curl:
  #   image: curlimages/curl:8.5.0
  #   command: curl -sSD - http://ats
  #   depends_on:
  #     - ats
