logging:
  formats:
    - name: "ltsv"
      format: 'timestamp:%<cqtq>	host:%<chi>	user:%<caun>	time:%<cqtn>	req:%<cqhm> %<pqu> %<cqpv>	s1:%<pssc>	c1:%<pscl>	s2:%<sssc>	c2:%<sscl>	h1:%<cqhl>	h2:%<pshl>	h3:%<pqhl>	h4:%<sshl>	xt:%<tts>	route:%<phr>	pfs:%<cfsc>	ss:%<pfsc>	crc:%<crc>	chm:%<chm>	cwr:%<cwr>	referer:%<{Referer}cqh>	psh_via:%<{Via}psh>	host_header:%<{Host}cqh>	x_forwarded_for:%<{X-Forwarded-For}cqh>	x_forwarded_proto:%<{X-Forwarded-Proto}cqh>	stms:%<stms>	stmsf:%<stmsf>  sca:%<sca>  surc:%<surc>  ssrc:%<ssrc> 	sstc:%<sstc>	shn:%<shn>	shi:%<shi>	ttms:%<ttms>	ttmsf:%<ttmsf>	phn:%<phn>	phi:%<phi>	phr:%<phr>	cache_control:%<{Cache-Control}ssh>	pqsi:%<pqsi>  pqsp:%<pqsp>	x_request_id:%<{X-Request-Id}cqh>	ua:%<{User-Agent}cqh>'
  logs:
    - filename: proxy.ltsv.log
      format: ltsv
      mode: ascii
